apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-api-inference-extension.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-api-inference-extension.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gateway-api-inference-extension.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc-ext-proc
      protocol: TCP
      port: {{ .Values.inferenceExtension.extProcPort | default 9002 }}
    - name: http-metrics
      protocol: TCP
      port: {{ .Values.inferenceExtension.metricsPort | default 9090 }}
    {{- if .Values.inferenceExtension.latencyPredictor.enabled }}
    - name: latency-predictor-training
      protocol: TCP
      port: {{ .Values.inferenceExtension.latencyPredictor.trainingServer.port }}
      targetPort: {{ .Values.inferenceExtension.latencyPredictor.trainingServer.port }}
    {{- range $i := until (int .Values.inferenceExtension.latencyPredictor.predictionServers.count) }}
    - name: latency-predictor-{{ add $i 1 }}
      protocol: TCP
      port: {{ add $.Values.inferenceExtension.latencyPredictor.predictionServers.startPort $i }}
      targetPort: {{ add $.Values.inferenceExtension.latencyPredictor.predictionServers.startPort $i }}
    {{- end }}
    {{- end }}
    {{- with .Values.inferenceExtension.extraServicePorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  type: ClusterIP